version: "3.3"
services:
  text-generation-webui:
    build:
      context: .
      args:
        # specify which cuda version your card supports: https://developer.nvidia.com/cuda-gpus
        TORCH_CUDA_ARCH_LIST: ${TORCH_CUDA_ARCH_LIST}
        WEBUI_VERSION: ${WEBUI_VERSION}
    env_file: .env
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
      - "${HOST_API_PORT}:${CONTAINER_API_PORT}"
      - "${HOST_API_STREAM_PORT}:${CONTAINER_API_STREAM_PORT}"
    stdin_open: true
    tty: true
    volumes:
      - /opt/docker/txtgen/characters:/app/characters
      - /opt/docker/txtgen/extensions:/app/extensions
      - /opt/docker/txtgen/loras:/app/loras
      - /opt/docker/txtgen/models:/app/models
      - /opt/docker/txtgen/presets:/app/presets
      - /opt/docker/txtgen/prompts:/app/prompts
      - /opt/docker/txtgen/softprompts:/app/softprompts
      - /opt/docker/txtgen/training:/app/training
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
